(()=>{
'use strict';
const T=window.TM,e=T.el,N=window.TM11;
T.bootAdminV11=async()=>{
 T.$('pillText').textContent='STUDIO';T.$('kicker').textContent='MOBILE BROADCAST STUDIO';T.$('title').innerHTML='ТВОЙ<br><span>ЭФИР.</span>';
 T.$('lead').textContent='Управление музыкой, рекламой и эфиром. Команды отправляются слушателям с автоматическим резервным каналом.';
 T.$('disc').classList.add('hidden');T.$('micPanel').classList.remove('hidden');T.$('studioCard').classList.remove('hidden');T.$('playlistCard').classList.remove('hidden');T.$('note').classList.remove('hidden');
 T.$('leftLabel').textContent='СЛУШАТЕЛЕЙ';T.$('rightLabel').textContent='ЭФИР';e.left.textContent='0';e.right.textContent='OFF';
 const ms=T.$('micState'),mm=T.$('micMeter'),copy=T.$('copyBtn'),rows=T.$('playlistRows'),state=T.$('playlistState'),head=T.$('playlistCard').querySelector('.playlist-title span');
 if(head)head.textContent='УПРАВЛЕНИЕ РАДИО';N.setSyncLabel('CONNECTING');
 let mic,stopMeter,mode='music',busy=false,wake=null,anchorTrack=0,anchorWall=Date.now(),modeStartedWall=0,special=null,revision=Date.now(),manualAd=0,afterLiveTrack=0,bus;
 const listeners=new Map(),pcs=new Map(),pendingIce=new Map();
 const bump=()=>++revision;
 function stateAt(){return T.timelineState(anchorTrack,anchorWall,Date.now())}
 function count(){const n=Date.now();for(const [id,t] of listeners)if(n-t>32000)listeners.delete(id);e.left.textContent=listeners.size;return listeners.size}
 function payload(to){const sentAt=Date.now();if(mode==='live')return{type:'state',to,mode:'live',revision,sentAt,position:0};if(mode!=='music'&&special)return{type:'state',to,mode,revision,sentAt,position:Math.max(0,(Date.now()-modeStartedWall)/1000),...special};const s=stateAt();return{type:'state',to,mode:'music',revision,sentAt,segment:s.segment,track:s.track,ad:s.ad,nextTrack:s.nextTrack,sourceTrack:s.sourceTrack,afterJingle:!!s.afterJingle,position:Number(s.offset)||0,dur:s.dur}}
 const broadcast=()=>N.publish(payload());
 const burst=()=>{broadcast();setTimeout(broadcast,260);setTimeout(broadcast,800);if(bus)setTimeout(()=>bus.pollNow(),150)};
 function closePc(id){const pc=pcs.get(id);if(pc){try{pc.close()}catch(_){}pcs.delete(id)}pendingIce.delete(id)}
 async function offerTo(id){if(!mic||mode!=='live')return;closePc(id);let servers;try{servers=await T.getIce()}catch(_){T.setStatus('warn','TURN недоступен — музыка работает, эфир пока нет');return}const pc=new RTCPeerConnection({iceServers:servers,sdpSemantics:'unified-plan',bundlePolicy:'max-bundle'});pcs.set(id,pc);pendingIce.set(id,[]);mic.getTracks().forEach(t=>pc.addTrack(t,mic));pc.onicecandidate=ev=>{if(ev.candidate)N.publish({type:'ice',from:'admin',to:id,candidate:ev.candidate.toJSON?ev.candidate.toJSON():ev.candidate})};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState))closePc(id)};try{const off=await pc.createOffer();await pc.setLocalDescription(off);await N.publish({type:'offer',from:'admin',to:id,sdp:pc.localDescription.sdp,revision})}catch(_){}}
 async function onMessage(m){if(m.type==='join'||m.type==='heartbeat'||m.type==='sync-request'){if(m.id){listeners.set(m.id,Date.now());count()}if(m.type!=='heartbeat'&&m.id){await N.publish(payload(m.id));if(mode==='live'&&mic)setTimeout(()=>offerTo(m.id),220)}return}if(m.type==='answer'&&m.to==='admin'){const pc=pcs.get(m.from);if(pc)try{await pc.setRemoteDescription({type:'answer',sdp:m.sdp});const q=pendingIce.get(m.from)||[];for(const c of q)try{await pc.addIceCandidate(c)}catch(_){}pendingIce.set(m.from,[])}catch(_){}return}if(m.type==='ice'&&m.to==='admin'&&m.candidate){const pc=pcs.get(m.from);if(pc&&pc.remoteDescription)try{await pc.addIceCandidate(m.candidate)}catch(_){}else{const q=pendingIce.get(m.from)||[];q.push(m.candidate);pendingIce.set(m.from,q)}}}
 async function requestWake(){if(document.visibilityState!=='visible'||!('wakeLock'in navigator)||wake)return;try{wake=await navigator.wakeLock.request('screen');wake.addEventListener('release',()=>{wake=null})}catch(_){wake=null}}
 bus=N.createBus(onMessage,ok=>{N.setSyncLabel(ok?'ONLINE':'RECONNECT');if(!busy)T.setStatus(ok?'ok':'warn',ok?'Студия готова • управление онлайн':'Восстанавливаю управление…');if(ok){broadcast();requestWake()}});
 function setSpecial(newMode,st){mode=newMode;modeStartedWall=Date.now();special={segment:st.segment,track:st.track,ad:st.ad,nextTrack:st.nextTrack,sourceTrack:st.sourceTrack,afterJingle:!!st.afterJingle,dur:st.dur};bump();draw();burst()}
 function setMusic(track){anchorTrack=track;anchorWall=Date.now();mode='music';modeStartedWall=0;special=null;bump();draw();burst()}
 function render(){const cp=stateAt(),info=T.titleFor(cp),next=T.nextTrackFrom(cp,anchorTrack),n=T.TRACKS[next];rows.innerHTML='';const r1=document.createElement('div');r1.className='track-row';r1.innerHTML='<div class="track-num">›</div><div class="track-info"><strong></strong><small></small></div><button class="track-play">СЛЕДУЮЩИЙ ТРЕК</button>';r1.querySelector('strong').textContent=info.title;r1.querySelector('small').textContent='ДАЛЬШЕ: '+n.title;const b1=r1.querySelector('button');b1.disabled=busy||mode!=='music';b1.onclick=skipNext;rows.appendChild(r1);const r2=document.createElement('div');r2.className='track-row';r2.innerHTML='<div class="track-num">AD</div><div class="track-info"><strong>Рекламный блок</strong><small>РЕКЛАМНЫЙ ДЖИНГЛ → РЕКЛАМА → МУЗЫКА</small></div><button class="track-play">ВКЛЮЧИТЬ РЕКЛАМУ</button>';const b2=r2.querySelector('button');b2.disabled=busy||mode!=='music';b2.onclick=playAdNow;rows.appendChild(r2)}
 function draw(){const cp=stateAt();e.btn.disabled=busy;e.btn.classList.toggle('on',mode==='live');e.btnText.textContent=mode==='live'?'ЗАВЕРШИТЬ ЭФИР':busy?'ПОДОЖДИ…':'ВЫЙТИ В ЭФИР';e.right.textContent=mode==='live'?'ON AIR':mode==='music'?'OFF':special?.segment==='ad'||special?.segment==='adJingle'?'AD':'JINGLE';ms.textContent=mic?'ACTIVE':'OFF';T.ui(mode==='music'?'music':mode,special||cp);render();state.textContent=busy?'ВЫПОЛНЯЮ':mode==='live'?'ЭФИР':'CONTROL'}
 const run=st=>T.playOneShot({...st,offset:0});
 async function skipNext(){if(busy||mode!=='music')return;const target=T.nextTrackFrom(stateAt(),anchorTrack);busy=true;draw();T.setStatus('warn','Переключаю трек…');setMusic(target);busy=false;draw();burst();T.setStatus('ok','Сейчас играет: '+T.TRACKS[target].title)}
 async function playAdNow(){if(busy||mode!=='music')return;busy=true;const target=T.nextTrackFrom(stateAt(),anchorTrack),ad=manualAd++%T.ADS.length;draw();setSpecial('manualAd',{segment:'adJingle',ad,sourceTrack:null,afterJingle:false,nextTrack:target,dur:T.AD_JINGLE_DUR});T.setStatus('live','Рекламный джингл…');await run({segment:'adJingle',ad,nextTrack:target,dur:T.AD_JINGLE_DUR});setSpecial('manualAd',{segment:'ad',ad,sourceTrack:null,afterJingle:false,nextTrack:target,dur:T.AD_DURS[ad]});T.setStatus('live','Реклама…');await run({segment:'ad',ad,nextTrack:target,dur:T.AD_DURS[ad]});setMusic(target);busy=false;draw();burst();T.setStatus('ok','Реклама закончилась • '+T.TRACKS[target].title)}
 async function startAir(){if(busy||mode==='live')return;busy=true;afterLiveTrack=T.nextTrackFrom(stateAt(),anchorTrack);draw();T.setStatus('warn','Запрашиваю микрофон…');try{await T.unlock();try{await T.getIce()}catch(x){throw Error(x.message==='TURN_KEY_MISSING'?'TURN_KEY_MISSING':'TURN_FAIL')}mic=await navigator.mediaDevices.getUserMedia({video:false,audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});stopMeter=T.meter(mic,l=>mm.style.width=Math.max(3,Math.round(l*100))+'%');await requestWake();setSpecial('intro',{segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});T.setStatus('live','Джингл перед эфиром…');await run({segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});mode='live';modeStartedWall=Date.now();special=null;bump();busy=false;draw();burst();for(const id of listeners.keys())offerTo(id);T.setStatus('live','ТЫ В ПРЯМОМ ЭФИРЕ')}catch(x){if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';busy=false;mode='music';special=null;anchorTrack=afterLiveTrack;anchorWall=Date.now();bump();draw();burst();T.setStatus('bad',x?.message==='TURN_KEY_MISSING'?'Для эфира нужна ссылка с TURN':x?.name==='NotAllowedError'?'Нет доступа к микрофону':'Не удалось включить прямой эфир')}}
 async function stopAir(){if(busy||mode!=='live')return;busy=true;for(const id of listeners.keys())N.publish({type:'close-live',to:id});for(const id of [...pcs.keys()])closePc(id);if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';setSpecial('outro',{segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});T.setStatus('live','Джингл после эфира…');await run({segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});setMusic(afterLiveTrack);busy=false;draw();burst();T.setStatus('ok','Музыка снова играет • студия готова')}
 e.btn.onclick=()=>mode==='live'?stopAir():startAir();
 copy.onclick=async()=>{let k='';try{k=localStorage.getItem('tommart_turn_key')||''}catch(_){}const u=new URL(location.origin+location.pathname);if(k)u.searchParams.set('turn',k);try{await navigator.clipboard.writeText(u.toString());copy.textContent='СКОПИРОВАНО';setTimeout(()=>copy.textContent='КОПИРОВАТЬ',1500)}catch(_){}};
 setInterval(()=>{count();broadcast()},2200);setInterval(()=>N.publish({type:'admin-ping',revision}),9000);
 const revive=()=>{if(document.visibilityState!=='visible')return;bus.restart();requestWake();setTimeout(()=>{burst();for(const id of listeners.keys())if(mode==='live'&&mic)offerTo(id)},300)};
 document.addEventListener('visibilitychange',revive);window.addEventListener('pageshow',revive);window.addEventListener('online',revive);window.addEventListener('focus',revive);
 await requestWake();draw();burst();
};
})();