(()=>{
const CFG={host:'tommart-moldova-studio-91c4e2d7a8',metered:'tommart-radio.metered.live',region:'europe',reconnect:2500};
const TRACKS=[
 {file:'%d0%9c%d0%be%d0%bb%d0%b4%d0%b0%d0%b2%d1%81%d0%ba%d0%b0%d1%8f%20-%20%d0%9c%d0%be%d0%bb%d0%b4%d0%b0%d0%b2%d1%81%d0%ba%d0%b0%d1%8f.mp3.mp3',title:'Молдавская — Молдавская'},
 {file:'Kleopatra_Stratan_-_Ghi_Gicu_(musportal.org).mp3',title:'Cleopatra Stratan — Ghi Gicu'}
];
const JINGLE={file:'gemini_generated_video_5EC56A5E.mp3',title:'TomMart Jingle'};
const GLOBAL_ANCHOR=Date.UTC(2026,0,1,0,0,0);
const pathFor=f=>'music/'+encodeURIComponent(f);
const IS_ADMIN=new URLSearchParams(location.search).get('admin')==='1';
const $=id=>document.getElementById(id);
const btn=$('mainBtn'),btnText=$('mainBtnText'),dot=$('dot'),statusText=$('statusText'),leftValue=$('leftValue'),rightValue=$('rightValue'),chip=$('chip'),disc=$('disc'),nowTitle=$('nowTitle'),nowSub=$('nowSub'),music=$('musicAudio'),live=$('liveAudio');
function readKey(){const p=new URLSearchParams(location.search),k=p.get('turn');if(k){try{localStorage.setItem('tommart_turn_key',k)}catch(_){}p.delete('turn');try{history.replaceState(null,'',location.pathname+(p.toString()?'?'+p:''))}catch(_){}return k}try{return localStorage.getItem('tommart_turn_key')||''}catch(_){return''}}
async function getIce(){const k=readKey();if(!k)throw Error('TURN_KEY_MISSING');const u=new URL('https://'+CFG.metered+'/api/v1/turn/credentials');u.searchParams.set('apiKey',k);u.searchParams.set('region',CFG.region);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('TURN '+r.status);const x=await r.json();if(!Array.isArray(x)||!x.length)throw Error('TURN_EMPTY');return x}
const peerOpts=iceServers=>({debug:1,config:{iceServers,sdpSemantics:'unified-plan'}});
function setStatus(kind,text){dot.className='dot '+(kind||'');statusText.textContent=text}
function setNow(kind,trackIndex){if(kind==='live'){nowTitle.textContent='Прямой эфир TomMart';nowSub.textContent='Живой микрофон студии';chip.textContent='ON AIR';chip.classList.add('hot');return}if(kind==='jingle'){nowTitle.textContent='TomMart Jingle';nowSub.textContent='Фирменный джингл';chip.textContent='JINGLE';chip.classList.add('hot');return}const t=TRACKS[trackIndex]||TRACKS[0];nowTitle.textContent=t.title;nowSub.textContent='Настоящий трек • MP3';chip.textContent=IS_ADMIN?'STUDIO':'24/7';chip.classList.remove('hot')}
function ui(mode,trackIndex=0,wanted=true){disc.classList.toggle('live',mode==='live');if(mode==='live'){if(!IS_ADMIN)leftValue.textContent='LIVE';setNow('live');btnText.textContent=IS_ADMIN?'ЗАВЕРШИТЬ ЭФИР':'СЛУШАЮ LIVE'}else if(mode==='intro'||mode==='outro'||mode==='switching'||mode==='jingle'){if(!IS_ADMIN)leftValue.textContent='JINGLE';setNow('jingle');if(!IS_ADMIN)btnText.textContent='СЛУШАЮ TOMMART'}else{if(!IS_ADMIN)leftValue.textContent='MUSIC';setNow('music',trackIndex);if(!IS_ADMIN)btnText.textContent=wanted?'СЛУШАЮ TOMMART':'СЛУШАТЬ TOMMART'}}
let ac;function audioCtx(){if(!ac){const A=window.AudioContext||window.webkitAudioContext;ac=new A}return ac}async function unlock(){const c=audioCtx();if(c.state!=='running')try{await c.resume()}catch(_){}}
function meter(stream,cb){const c=audioCtx(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=512;src.connect(an);const d=new Uint8Array(an.frequencyBinCount);let raf;const run=()=>{an.getByteFrequencyData(d);let s=0;for(const x of d)s+=x;cb(Math.min(1,(s/d.length)/100));raf=requestAnimationFrame(run)};run();return()=>{cancelAnimationFrame(raf);try{src.disconnect()}catch(_){}}}
function probe(src,fallback){return new Promise(res=>{const a=new Audio();let done=false;const finish=v=>{if(done)return;done=true;res(v)};a.preload='metadata';a.onloadedmetadata=()=>finish(Number.isFinite(a.duration)&&a.duration>0?a.duration:fallback);a.onerror=()=>finish(fallback);a.src=src;setTimeout(()=>finish(fallback),7000)})}
let DURATIONS=[240,240],JINGLE_DURATION=4;async function loadDurations(){DURATIONS=await Promise.all(TRACKS.map(t=>probe(pathFor(t.file),240)));JINGLE_DURATION=await probe(pathFor(JINGLE.file),4)}
function timelineState(anchorTrack=0,anchorAt=GLOBAL_ANCHOR,now=Date.now()){const total=DURATIONS.reduce((a,b)=>a+b,0)+TRACKS.length*JINGLE_DURATION;let e=((now-anchorAt)/1000%total+total)%total;for(let n=0;n<TRACKS.length;n++){const idx=(anchorTrack+n)%TRACKS.length,d=DURATIONS[idx];if(e<d)return{segment:'track',track:idx,offset:e};e-=d;if(e<JINGLE_DURATION)return{segment:'jingle',nextTrack:(idx+1)%TRACKS.length,offset:e};e-=JINGLE_DURATION}return{segment:'track',track:anchorTrack,offset:0}}
async function setAudio(src,offset=0){if(music.src!==new URL(src,location.href).href)music.src=src;if(!music.duration||!Number.isFinite(music.duration))await new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;res()};music.addEventListener('loadedmetadata',f,{once:true});setTimeout(f,2500)});if(Number.isFinite(offset)&&offset>0&&music.duration)try{music.currentTime=Math.min(offset,Math.max(0,music.duration-.1))}catch(_){}try{await music.play();return true}catch(_){return false}}
function stopProgram(){try{music.pause()}catch(_){}music.onended=null}
async function playTrack(index,offset=0,onEnded){stopProgram();ui('music',index,true);const ok=await setAudio(pathFor(TRACKS[index].file),offset);music.onended=()=>onEnded&&onEnded(index);if(!ok)setStatus('warn','Нажми кнопку ещё раз, чтобы включить музыку')}
async function playJingle(offset=0,onEnded){stopProgram();ui('jingle');const ok=await setAudio(pathFor(JINGLE.file),offset);music.onended=()=>onEnded&&onEnded();if(!ok)setStatus('warn','Нажми кнопку ещё раз, чтобы включить джингл')}
async function loopTrack(index,offset=0){await playTrack(index,offset,()=>loopJingle((index+1)%TRACKS.length,0))}
async function loopJingle(nextTrack,offset=0){await playJingle(offset,()=>loopTrack(nextTrack,0))}
async function playGlobalProgram(){const st=timelineState();if(st.segment==='track')await loopTrack(st.track,st.offset);else await loopJingle(st.nextTrack,st.offset)}
async function bootListener(servers){let peer,control,call,wanted=false,mode='music',rt;function closeLive(){if(call){try{call.close()}catch(_){}call=null}try{live.pause()}catch(_){}live.srcObject=null}
async function apply(d){if(!d)return;mode=d.mode||'music';if(!wanted)return;if(mode==='intro'){closeLive();await playJingle(d.offset||0,()=>{stopProgram();setStatus('live','Джингл закончился • жду микрофон')});setStatus('live','Джингл перед прямым эфиром…');return}if(mode==='live'){stopProgram();ui('live');setStatus('live','Подключаю микрофон ведущего…');return}if(mode==='outro'){closeLive();await playJingle(d.offset||0,()=>{stopProgram();setStatus('live','Возвращаю музыку…')});setStatus('live','Финальный джингл…');return}if(mode==='switching'){closeLive();await playJingle(d.offset||0,()=>{stopProgram();setStatus('warn','Переключаю песню…')});setStatus('live','Джингл • следующая песня…');return}closeLive();if(d.segment==='jingle'){await loopJingle(d.nextTrack??0,d.offset||0);setStatus(control?.open?'ok':'warn','Джингл между песнями')}else{await loopTrack(d.track??0,d.offset||0);setStatus(control?.open?'ok':'warn',control?.open?'Музыка играет • студия на связи':'Музыка играет • студия офлайн')}}
function reconnect(){if(!wanted)return;clearTimeout(rt);rt=setTimeout(connect,CFG.reconnect)}function connect(){if(!wanted||!peer?.open||control?.open)return;rightValue.textContent='СВЯЗЬ…';control=peer.connect(CFG.host,{reliable:true,serialization:'json'});control.on('open',()=>{rightValue.textContent='ONLINE';setStatus('ok','Студия на связи');control.send({type:'ready'})});control.on('data',d=>{if(d?.type==='state')apply(d)});control.on('close',()=>{control=null;rightValue.textContent='OFFLINE';reconnect()});control.on('error',()=>{control=null;reconnect()})}
peer=new Peer(undefined,peerOpts(servers));peer.on('open',connect);peer.on('call',c=>{if(!wanted)return c.close();closeLive();call=c;stopProgram();ui('live');c.answer();c.on('stream',async s=>{live.srcObject=s;try{await live.play();setStatus('live','Ты слушаешь прямой эфир TomMart')}catch(_){btnText.textContent='ВКЛЮЧИТЬ ЗВУК LIVE';setStatus('warn','Эфир подключён — нажми кнопку')}});c.on('close',()=>{if(call===c)call=null});c.on('error',()=>setStatus('warn','Микрофон потерял связь'))});peer.on('error',e=>{if(e?.type==='peer-unavailable'){rightValue.textContent='OFFLINE';reconnect()}else setStatus('warn','Связь: '+(e?.type||'ошибка'))});btn.disabled=false;btnText.textContent='СЛУШАТЬ TOMMART';rightValue.textContent='ГОТОВО';setStatus('ok','Радио готово • нажми слушать');btn.onclick=async()=>{wanted=true;btn.disabled=true;await unlock();if(live.srcObject&&live.paused){try{await live.play()}catch(_){}btn.disabled=false;return}if(control?.open)control.send({type:'ready'});else{await playGlobalProgram();connect()}setTimeout(()=>btn.disabled=false,450)}}
async function bootAdmin(servers){$('pillText').textContent='STUDIO';$('kicker').textContent='MOBILE BROADCAST STUDIO';$('title').innerHTML='ТВОЙ<br><span>ЭФИР.</span>';$('lead').textContent='Выбирай песню из плейлиста или выходи в эфир. Перед каждой сменой песни и перед микрофоном звучит твой джингл.';$('disc').classList.add('hidden');$('micPanel').classList.remove('hidden');$('studioCard').classList.remove('hidden');$('playlistCard').classList.remove('hidden');$('note').classList.remove('hidden');$('leftLabel').textContent='СЛУШАТЕЛЕЙ';$('rightLabel').textContent='ЭФИР';leftValue.textContent='0';rightValue.textContent='OFF';const ps=$('peerState'),ms=$('micState'),mm=$('micMeter'),copy=$('copyBtn'),rows=$('playlistRows'),plState=$('playlistState');let peer,mic,stopMeter,mode='music',busy=false,wake,anchorTrack=0,anchorAt=GLOBAL_ANCHOR,lastSig='';const conns=new Map(),calls=new Map();
function renderPlaylist(active,segment){rows.innerHTML='';TRACKS.forEach((t,i)=>{const r=document.createElement('div');r.className='track-row';r.innerHTML='<div class="track-num">'+(i+1)+'</div><div class="track-info"><strong></strong><small>ПЕСНЯ</small></div><button class="track-play"></button>';r.querySelector('strong').textContent=t.title;const b=r.querySelector('button');const isPlaying=segment==='track'&&i===active&&mode==='music';b.textContent=isPlaying?'ИГРАЕТ':'ВКЛЮЧИТЬ';b.classList.toggle('active',isPlaying);b.disabled=busy||mode!=='music';b.onclick=()=>switchSong(i);rows.appendChild(r)})}
function count(){let n=0;conns.forEach(c=>{if(c.open)n++});leftValue.textContent=n;return n}function currentProgram(){return timelineState(anchorTrack,anchorAt)}function payload(){if(mode!=='music')return{type:'state',mode,at:Date.now()};const s=currentProgram();return{type:'state',mode:'music',segment:s.segment,track:s.track,nextTrack:s.nextTrack,offset:s.offset,at:Date.now()}}function send(c){if(c?.open)try{c.send(payload())}catch(_){}}function broadcast(){conns.forEach(send)}function closeCall(id){const c=calls.get(id);if(c){try{c.close()}catch(_){}calls.delete(id)}}function callOne(id){if(mode!=='live'||!mic||!peer?.open)return;closeCall(id);const c=peer.call(id,mic,{metadata:{source:'tommart-live'}});if(c){calls.set(id,c);c.on('close',()=>calls.delete(id));c.on('error',()=>calls.delete(id))}}
function draw(){const cp=currentProgram(),active=cp.segment==='track'?cp.track:(cp.nextTrack??anchorTrack);btn.disabled=!peer?.open||busy;btn.classList.toggle('on',mode==='live');btnText.textContent=mode==='live'?'ЗАВЕРШИТЬ ЭФИР':busy?'ПОДОЖДИ…':'ВЫЙТИ В ЭФИР';rightValue.textContent=mode==='live'?'ON AIR':mode==='music'?'OFF':'JINGLE';ms.textContent=mic?'ACTIVE':'OFF';if(mode==='music')ui('music',active);else ui(mode,active);renderPlaylist(active,cp.segment);plState.textContent=busy?'ПЕРЕКЛЮЧЕНИЕ':mode==='live'?'ЭФИР':'ГОТОВ'}
async function adminJingle(){stopProgram();await setAudio(pathFor(JINGLE.file),0);await new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;music.pause();res()};music.onended=f;setTimeout(f,(JINGLE_DURATION+1.5)*1000)})}
async function switchSong(index){if(busy||mode!=='music')return;busy=true;mode='switching';draw();broadcast();setStatus('live','Джингл • переключаю песню…');await adminJingle();anchorTrack=index;anchorAt=Date.now();mode='music';busy=false;draw();broadcast();setStatus('ok','Включена: '+TRACKS[index].title)}
async function startAir(){if(busy||mode==='live')return;busy=true;draw();setStatus('warn','Запрашиваю микрофон…');try{await unlock();mic=await navigator.mediaDevices.getUserMedia({video:false,audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});stopMeter=meter(mic,l=>mm.style.width=Math.max(3,Math.round(l*100))+'%');if('wakeLock'in navigator)try{wake=await navigator.wakeLock.request('screen')}catch(_){}mode='intro';draw();broadcast();setStatus('live','Твой джингл звучит у слушателей…');await adminJingle();mode='live';busy=false;draw();broadcast();conns.forEach((c,id)=>{if(c.open)callOne(id)});setStatus('live','ТЫ В ПРЯМОМ ЭФИРЕ')}catch(e){if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;busy=false;mode='music';broadcast();draw();setStatus('bad',e?.name==='NotAllowedError'?'Нет доступа к микрофону':'Не удалось включить микрофон')}}
async function stopAir(){if(busy||mode!=='live')return;busy=true;mode='outro';draw();calls.forEach((_,id)=>closeCall(id));if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';broadcast();setStatus('live','Джингл после эфира…');await adminJingle();const cp=currentProgram();anchorTrack=cp.segment==='track'?cp.track:(cp.nextTrack??anchorTrack);anchorAt=Date.now();mode='music';busy=false;broadcast();draw();setStatus('ok','Музыка снова играет • студия готова');if(wake)try{await wake.release()}catch(_){}}
btn.onclick=()=>mode==='live'?stopAir():startAir();copy.onclick=async()=>{let k='';try{k=localStorage.getItem('tommart_turn_key')||''}catch(_){}const u=new URL(location.origin+location.pathname);if(k)u.searchParams.set('turn',k);try{await navigator.clipboard.writeText(u.toString());copy.textContent='СКОПИРОВАНО';setTimeout(()=>copy.textContent='КОПИРОВАТЬ',1500)}catch(_){}};peer=new Peer(CFG.host,peerOpts(servers));peer.on('open',()=>{ps.textContent='ONLINE';draw();setStatus('ok','Студия онлайн • выбирай песню или выходи в эфир')});peer.on('connection',c=>{conns.set(c.peer,c);c.on('open',()=>{count();send(c);if(mode==='live'&&mic)setTimeout(()=>callOne(c.peer),150)});c.on('data',d=>{if(d?.type==='ready'){send(c);if(mode==='live'&&mic)setTimeout(()=>callOne(c.peer),150)}});c.on('close',()=>{conns.delete(c.peer);closeCall(c.peer);count()});c.on('error',()=>{conns.delete(c.peer);closeCall(c.peer);count()})});peer.on('error',e=>{ps.textContent=e?.type==='unavailable-id'?'BUSY':'ERROR';setStatus('bad',e?.type==='unavailable-id'?'Студия уже открыта на другом устройстве':'Ошибка PeerJS: '+(e?.type||'unknown'));draw()});setInterval(()=>{if(mode!=='music'||busy)return;const s=currentProgram(),sig=s.segment+':'+(s.track??s.nextTrack);if(sig!==lastSig){lastSig=sig;draw();broadcast()}},800);draw()}
(async()=>{if(IS_ADMIN)document.title='TomMart — Студия';try{await loadDurations();const s=await getIce();if(IS_ADMIN)await bootAdmin(s);else await bootListener(s)}catch(e){console.error(e);btn.disabled=true;btnText.textContent=e.message==='TURN_KEY_MISSING'?'НУЖНА НАСТРОЙКА TURN':'ОШИБКА СВЯЗИ';setStatus('bad',e.message==='TURN_KEY_MISSING'?'Открой специальную ссылку TomMart для первого запуска':'Не удалось подключить TURN');rightValue.textContent='ERROR'}})();
})();