(()=>{
'use strict';const T=window.TM,e=T.el;
T.ac=null;T.localKey='';T.playEpoch=0;
T.audioCtx=()=>{if(!T.ac){const A=window.AudioContext||window.webkitAudioContext;T.ac=new A}return T.ac};
T.unlock=async()=>{const c=T.audioCtx();if(c.state!=='running')try{await c.resume()}catch(_){}};
T.meter=(stream,cb)=>{const c=T.audioCtx(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=512;src.connect(an);const d=new Uint8Array(an.frequencyBinCount);let raf;const run=()=>{an.getByteFrequencyData(d);let s=0;for(const x of d)s+=x;cb(Math.min(1,(s/d.length)/100));raf=requestAnimationFrame(run)};run();return()=>{cancelAnimationFrame(raf);try{src.disconnect()}catch(_){}}};
T.srcFor=st=>st.segment==='track'?T.pathFor(T.TRACKS[st.track].file):st.segment==='radioJingle'?T.pathFor(T.RADIO_JINGLE.file):st.segment==='adJingle'?T.pathFor(T.AD_JINGLE.file):st.segment==='ad'?T.pathFor((T.ADS[st.ad]||T.ADS[0]).file):T.pathFor(T.TRACKS[0].file);
T.stateKey=st=>st?[st.segment,st.track??'',st.ad??'',st.nextTrack??'',st.sourceTrack??''].join(':'):'none';
T.stopProgram=()=>{T.playEpoch++;try{e.music.onended=null;e.music.pause();e.music.playbackRate=1}catch(_){}T.localKey=''};
T.setAudio=async(src,offset=0)=>{const abs=new URL(src,location.href).href;if(e.music.src!==abs)e.music.src=src;if(!e.music.duration||!Number.isFinite(e.music.duration))await new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;res()};e.music.addEventListener('loadedmetadata',f,{once:true});setTimeout(f,3500)});if(Number.isFinite(offset)&&offset>=0&&e.music.duration)try{e.music.currentTime=Math.min(offset,Math.max(0,e.music.duration-.08))}catch(_){}try{await e.music.play();return true}catch(_){return false}};
T.nextStateAfter=st=>{if(st.segment==='track'){const next=T.nextTrackIndex(st.track),doAd=T.adAfter(st.track),doJ=T.jingleAfter(st.track),ad=T.adIndexAfter(st.track);if(doAd)return{segment:'adJingle',ad,sourceTrack:st.track,afterJingle:false,nextTrack:next,offset:0,dur:T.AD_JINGLE_DUR};if(doJ)return{segment:'radioJingle',sourceTrack:st.track,nextTrack:next,offset:0,dur:T.RADIO_JINGLE_DUR};return{segment:'track',track:next,sourceTrack:next,offset:0,dur:T.TRACK_DURS[next]}}if(st.segment==='adJingle')return{segment:'ad',ad:st.ad,sourceTrack:st.sourceTrack,afterJingle:false,nextTrack:st.nextTrack,offset:0,dur:T.AD_DURS[st.ad]};if(st.segment==='ad')return{segment:'track',track:st.nextTrack??0,sourceTrack:st.nextTrack??0,offset:0,dur:T.TRACK_DURS[st.nextTrack??0]};if(st.segment==='radioJingle')return{segment:'track',track:st.nextTrack??0,sourceTrack:st.nextTrack??0,offset:0,dur:T.TRACK_DURS[st.nextTrack??0]};return{segment:'track',track:0,sourceTrack:0,offset:0,dur:T.TRACK_DURS[0]}};
T.playState=async(st,opt={})=>{if(!st)return false;const key=T.stateKey(st),src=T.srcFor(st),abs=new URL(src,location.href).href,same=key===T.localKey&&e.music.src===abs&&!e.music.paused;T.ui('music',st,true);if(same&&!opt.force){const wanted=Number(st.offset)||0,diff=(e.music.currentTime||0)-wanted;if(Math.abs(diff)>0.22)try{e.music.currentTime=wanted}catch(_){}else if(Math.abs(diff)>0.045)try{e.music.playbackRate=diff>0?0.97:1.03;setTimeout(()=>{try{e.music.playbackRate=1}catch(_){}},650)}catch(_){}return true}T.stopProgram();const epoch=T.playEpoch;T.localKey=key;const ok=await T.setAudio(src,Number(st.offset)||0);if(epoch!==T.playEpoch)return false;try{e.music.playbackRate=1}catch(_){}if(opt.autonext===false)e.music.onended=null;else e.music.onended=()=>{if(epoch!==T.playEpoch)return;T.playState(T.nextStateAfter(st),{force:true})};if(!ok)T.setStatus('warn','Нажми кнопку ещё раз, чтобы включить звук');else if(opt.status)T.setStatus('ok',opt.status);return ok};
T.playGlobalProgram=()=>T.playState(T.timelineState(0,T.GLOBAL_ANCHOR),{force:true});
T.playOneShot=async st=>{T.stopProgram();const epoch=T.playEpoch;const ok=await T.setAudio(T.srcFor(st),Number(st.offset)||0);if(!ok)return false;await new Promise(res=>{let done=false;const finish=()=>{if(done)return;done=true;if(epoch===T.playEpoch){try{e.music.onended=null;e.music.pause()}catch(_){}}res()};e.music.onended=finish;setTimeout(finish,((st.dur||5)+1.1)*1000)});return true};
})();