(()=>{
'use strict';
const N=window.TM11=window.TM11||{};
N.ROOM='tommart-radio-013b88770c4c666505cac664ed9d43d8-v11';
N.TOPIC='https://ntfy.sh/'+N.ROOM;
N.SSE=N.TOPIC+'/sse?since=30s';
N.POLL=N.TOPIC+'/json?poll=1&since=20s';
N.BOOT=Date.now();
N.delay=ms=>new Promise(r=>setTimeout(r,ms));
N.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
N.persistentId=()=>{try{let id=localStorage.getItem('tommart_listener_id_v11');if(!id){id=(crypto.randomUUID?crypto.randomUUID():'u-'+Math.random().toString(36).slice(2)+Date.now().toString(36));localStorage.setItem('tommart_listener_id_v11',id)}return id}catch(_){return'u-'+Math.random().toString(36).slice(2)+Date.now().toString(36)}};
let queue=Promise.resolve();
N.publish=(msg)=>{const packet={...msg,room:N.ROOM,ts:Date.now(),msgId:msg.msgId||('m-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7))};const send=()=>fetch(N.TOPIC,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(packet),cache:'no-store',keepalive:true});queue=queue.then(async()=>{for(let i=0;i<3;i++){try{const r=await send();if(r.ok)return true}catch(_){}await N.delay(350*(i+1))}return false});return queue};
N.createBus=(handler,statusCb)=>{let es=null,closed=false,retryTimer=null,polling=false,lastGood=0,lastStatus=null;const seen=new Set(),order=[];const remember=id=>{if(!id||seen.has(id))return false;seen.add(id);order.push(id);if(order.length>350){const x=order.shift();seen.delete(x)}return true};const notify=()=>{const ok=Date.now()-lastGood<9000;if(ok===lastStatus)return;lastStatus=ok;try{statusCb&&statusCb(ok)}catch(_){}};const parse=o=>{if(!o||o.event!=='message'||!o.message)return;if(o.id&&!remember(o.id))return;try{const m=JSON.parse(o.message);if(m.room!==N.ROOM||!m.ts||m.ts<N.BOOT-120000)return;lastGood=Date.now();handler(m,o);notify()}catch(_){}};const closeSse=()=>{if(es){try{es.close()}catch(_){}es=null}};const open=()=>{if(closed)return;clearTimeout(retryTimer);closeSse();try{es=new EventSource(N.SSE);es.onopen=()=>{lastGood=Date.now();notify()};es.onmessage=ev=>{try{parse(JSON.parse(ev.data))}catch(_){}};es.onerror=()=>{closeSse();retryTimer=setTimeout(open,1800)}}catch(_){retryTimer=setTimeout(open,1800)}};const poll=async()=>{if(closed||polling)return;polling=true;try{const r=await fetch(N.POLL,{cache:'no-store'});if(!r.ok)throw Error('poll');const text=await r.text();for(const line of text.split('\n'))if(line.trim())try{parse(JSON.parse(line))}catch(_){}lastGood=Date.now();notify()}catch(_){notify()}finally{polling=false}};const revive=()=>{if(closed)return;open();poll()};open();poll();const pt=setInterval(poll,2600),ht=setInterval(()=>{if(Date.now()-lastGood>12000)open();notify()},5000);const vis=()=>{if(document.visibilityState==='visible')setTimeout(revive,120)};document.addEventListener('visibilitychange',vis);window.addEventListener('pageshow',revive);window.addEventListener('online',revive);window.addEventListener('focus',revive);return{restart:revive,pollNow:poll,close:()=>{closed=true;clearInterval(pt);clearInterval(ht);clearTimeout(retryTimer);closeSse();document.removeEventListener('visibilitychange',vis);window.removeEventListener('pageshow',revive);window.removeEventListener('online',revive);window.removeEventListener('focus',revive)}}};
N.setSyncLabel=text=>{const T=window.TM,card=T.$('studioCard'),ps=T.$('peerState');if(card){const first=card.querySelector('.row span');if(first)first.textContent='TomMart Control'}if(ps)ps.textContent=text};
})();