(()=>{
'use strict';
const T=window.TM,e=T.el,M=window.TM13;
T.bootListenerV13=async()=>{
 const id=M.makeId();let wanted=false,latest=null,lastSid='',halfRtt=.08,link=null,livePc=null,pendingIce=[],lastStateAt=0;
 function closeLive(){if(livePc){try{livePc.close()}catch(_){}livePc=null}pendingIce=[];try{e.live.pause()}catch(_){}e.live.srcObject=null}
 function targetPos(s,extra=0){let p=Number(s.position)||0;if(s.sentAt&&Math.abs(Date.now()-Number(s.sentAt))<300000)p+=Math.max(0,Math.min(2,(Date.now()-Number(s.sentAt))/1000));p+=extra;return Math.max(0,Math.min(p,Math.max(0,(Number(s.dur)||9999)-.08)))}
 async function apply(s,extra=0){if(!s||s.type!=='state')return;latest=s;lastStateAt=Date.now();if(!wanted)return;if(s.mode==='live'||s.segment==='live'){T.stopProgram();T.ui('live');T.setStatus('live','Подключаю прямой эфир…');return}closeLive();const st={sid:s.sid,segment:s.segment,track:s.track,ad:s.ad,nextTrack:s.nextTrack,dur:s.dur};const force=String(s.sid)!==String(lastSid);lastSid=s.sid;const ok=await T.playSegment(st,targetPos(s,extra),{force});if(ok)T.setStatus('ok','TomMart • синхронизация онлайн');else T.setStatus('warn','Нажми СЛУШАТЬ ещё раз для звука')}
 async function handleOffer(m){if(!wanted)return;closeLive();let ice;try{ice=await T.getIce()}catch(_){T.setStatus('warn','Для прямого эфира нужна TURN-настройка');return}const pc=new RTCPeerConnection({iceServers:ice,sdpSemantics:'unified-plan',bundlePolicy:'max-bundle'});livePc=pc;pc.ontrack=async ev=>{const s=ev.streams?.[0]||new MediaStream([ev.track]);e.live.srcObject=s;try{await e.live.play();T.setStatus('live','Ты слушаешь прямой эфир TomMart')}catch(_){T.setStatus('warn','Эфир подключён — нажми кнопку')}};pc.onicecandidate=ev=>{if(ev.candidate)link.pub(M.TOPICS.adminSignal,{type:'ice',from:id,candidate:ev.candidate.toJSON?ev.candidate.toJSON():ev.candidate})};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))closeLive()};try{await pc.setRemoteDescription({type:'offer',sdp:m.sdp});for(const c of pendingIce.splice(0))try{await pc.addIceCandidate(c)}catch(_){}const ans=await pc.createAnswer();await pc.setLocalDescription(ans);link.pub(M.TOPICS.adminSignal,{type:'answer',from:id,sdp:pc.localDescription.sdp})}catch(_){T.setStatus('warn','Не удалось подключить LIVE')}}
 function onMessage(topic,m){if(topic===M.TOPICS.state&&m.type==='state'){apply(m,halfRtt);return}if(topic===M.pong(id)&&m.type==='pong'&&m.state){const rtt=Math.max(0,(performance.now()-Number(m.t0))/1000);halfRtt=Math.min(.6,rtt/2);apply(m.state,halfRtt);return}if(topic===M.signal(id)){if(m.type==='offer')handleOffer(m);else if(m.type==='ice'&&m.candidate){if(livePc&&livePc.remoteDescription)livePc.addIceCandidate(m.candidate).catch(()=>{});else pendingIce.push(m.candidate)}else if(m.type==='close')closeLive()}}
 link=M.connect('listener',id,onMessage,ok=>{e.right.textContent=ok?'ONLINE':'СВЯЗЬ…';M.setSyncLabel(ok?'ONLINE':'RECONNECT');if(ok&&wanted){link.pub(M.TOPICS.presence,{type:'join',id,at:Date.now()});setTimeout(()=>ping(),180)}});
 function ping(){if(!wanted||!link?.connected())return;link.pub(M.TOPICS.ping,{type:'ping',id,t0:performance.now()})}
 function presence(){if(wanted&&link?.connected())link.pub(M.TOPICS.presence,{type:'presence',id,at:Date.now()})}
 e.btn.disabled=false;e.btnText.textContent='СЛУШАТЬ TOMMART';e.right.textContent='ГОТОВО';T.setStatus('ok','Радио готово • нажми слушать');
 e.btn.onclick=async()=>{wanted=true;e.btn.disabled=true;await T.unlock();if(e.live.srcObject&&e.live.paused){try{await e.live.play()}catch(_){}e.btn.disabled=false;return}presence();ping();if(latest)await apply(latest,halfRtt);else T.setStatus('warn','Жду состояние студии…');setTimeout(()=>e.btn.disabled=false,350)};
 setInterval(presence,7000);setInterval(ping,4500);setInterval(()=>{if(wanted&&Date.now()-lastStateAt>6000&&link?.connected())ping()},3000);
 const revive=()=>{if(!wanted)return;presence();ping();if(latest)setTimeout(()=>apply(latest,halfRtt),200)};document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')revive()});window.addEventListener('pageshow',revive);window.addEventListener('online',revive);
 window.addEventListener('beforeunload',()=>{try{link?.end()}catch(_){}closeLive()});
};
})();
