(()=>{
'use strict';
const T=window.TM,e=T.el,N=window.TM12;
T.bootListenerV12=async()=>{
 const id=N.persistentId();let wanted=false,lastRevision=0,lastSentAt=0,livePc=null,pendingIce=[],bus;
 function closeLive(){if(livePc){try{livePc.close()}catch(_){}livePc=null}pendingIce=[];try{e.live.pause()}catch(_){}e.live.srcObject=null}
 function correctedPosition(m){const base=Number(m.position)||0;const age=Number(m.sentAt)?N.clamp((Date.now()-Number(m.sentAt))/1000,0,4):0;return base+age}
 async function applyState(m){if(!wanted||(m.to&&m.to!==id))return;const rev=Number(m.revision)||0,sent=Number(m.sentAt)||Number(m.ts)||0;if(rev<lastRevision)return;if(rev===lastRevision&&sent&&sent<lastSentAt)return;if(rev>lastRevision)lastRevision=rev;if(sent)lastSentAt=sent;if(m.mode==='live'){T.stopProgram();T.ui('live');T.setStatus('live','Подключаю прямой эфир…');return}if(m.mode!=='music'&&m.segment){closeLive();const dur=Number(m.dur)||5,st={segment:m.segment,track:m.track,ad:m.ad,nextTrack:m.nextTrack,sourceTrack:m.sourceTrack,dur,offset:Math.min(correctedPosition(m),Math.max(0,dur-.08))};T.ui(m.mode,st,true);await T.playState(st,{force:T.stateKey(st)!==T.localKey,autonext:false});T.setStatus('live',st.segment==='adJingle'?'Рекламный джингл…':st.segment==='ad'?'Реклама…':'Джингл TomMart…');return}if(m.mode==='music'){closeLive();const st={segment:m.segment||'track',track:m.track,ad:m.ad,nextTrack:m.nextTrack,sourceTrack:m.sourceTrack,offset:correctedPosition(m),dur:m.dur};await T.playState(st,{force:T.stateKey(st)!==T.localKey,status:'TomMart • синхронизация онлайн'})}}
 async function handleOffer(m){if(!wanted||m.to!==id)return;closeLive();let servers;try{servers=await T.getIce()}catch(_){T.setStatus('warn','Для прямого эфира нужна TURN-настройка');return}const pc=new RTCPeerConnection({iceServers:servers,sdpSemantics:'unified-plan',bundlePolicy:'max-bundle'});livePc=pc;pc.ontrack=async ev=>{const s=ev.streams?.[0]||new MediaStream([ev.track]);e.live.srcObject=s;try{await e.live.play();T.setStatus('live','Ты слушаешь прямой эфир TomMart')}catch(_){e.btnText.textContent='ВКЛЮЧИТЬ ЗВУК LIVE';T.setStatus('warn','Эфир подключён — нажми кнопку')}};pc.onicecandidate=ev=>{if(ev.candidate)N.publish({type:'ice',from:id,to:'admin',candidate:ev.candidate.toJSON?ev.candidate.toJSON():ev.candidate})};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState))closeLive()};try{await pc.setRemoteDescription({type:'offer',sdp:m.sdp});for(const c of pendingIce.splice(0))try{await pc.addIceCandidate(c)}catch(_){}const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await N.publish({type:'answer',from:id,to:'admin',sdp:pc.localDescription.sdp,revision:m.revision})}catch(_){T.setStatus('warn','Не удалось подключить микрофон')}}
 async function onMessage(m){if(m.type==='state')return applyState(m);if(m.type==='offer')return handleOffer(m);if(m.type==='ice'&&m.to===id&&m.candidate){if(livePc&&livePc.remoteDescription)try{await livePc.addIceCandidate(m.candidate)}catch(_){}else pendingIce.push(m.candidate);return}if(m.type==='close-live'&&m.to===id)closeLive()}
 bus=N.createBus(onMessage,ok=>{e.right.textContent=ok?'ONLINE':'СВЯЗЬ…';N.setSyncLabel(ok?'ONLINE':'RECONNECT');if(ok&&wanted){N.publish({type:'join',id});N.publish({type:'sync-request',id})}});
 e.btn.disabled=false;e.btnText.textContent='СЛУШАТЬ TOMMART';e.right.textContent='ГОТОВО';T.setStatus('ok','Радио готово • нажми слушать');
 e.btn.onclick=async()=>{wanted=true;e.btn.disabled=true;await T.unlock();if(e.live.srcObject&&e.live.paused){try{await e.live.play()}catch(_){}e.btn.disabled=false;return}await T.playGlobalProgram();await N.publish({type:'join',id});await N.publish({type:'sync-request',id});bus.pollNow();setTimeout(()=>e.btn.disabled=false,400)};
 setInterval(()=>{if(wanted)N.publish({type:'heartbeat',id})},8000);
 setInterval(()=>{if(wanted)N.publish({type:'sync-request',id})},14000);
 const revive=()=>{if(!wanted)return;bus.restart();setTimeout(()=>{N.publish({type:'join',id});N.publish({type:'sync-request',id})},220)};
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')revive()});window.addEventListener('pageshow',revive);window.addEventListener('online',revive);window.addEventListener('focus',revive);
 window.addEventListener('beforeunload',()=>{try{bus.close()}catch(_){}closeLive()});
};
})();