(()=>{
'use strict';
const T=window.TM,e=T.el;
T.ac=null;T.localKey='';T.playEpoch=0;
T.audioCtx=()=>{if(!T.ac){const A=window.AudioContext||window.webkitAudioContext;T.ac=new A}return T.ac};
T.unlock=async()=>{const c=T.audioCtx();if(c.state!=='running')try{await c.resume()}catch(_){}};
T.meter=(stream,cb)=>{const c=T.audioCtx(),src=c.createMediaStreamSource(stream),an=c.createAnalyser();an.fftSize=512;src.connect(an);const d=new Uint8Array(an.frequencyBinCount);let raf;const run=()=>{an.getByteFrequencyData(d);let s=0;for(const x of d)s+=x;cb(Math.min(1,(s/d.length)/100));raf=requestAnimationFrame(run)};run();return()=>{cancelAnimationFrame(raf);try{src.disconnect()}catch(_){}}};
T.srcFor=st=>st.segment==='track'?T.pathFor(T.TRACKS[st.track].file):st.segment==='radioJingle'?T.pathFor(T.RADIO_JINGLE.file):st.segment==='adJingle'?T.pathFor(T.AD_JINGLE.file):st.segment==='ad'?T.pathFor((T.ADS[st.ad]||T.ADS[0]).file):T.pathFor(T.TRACKS[0].file);
T.stateKey=st=>st?[st.segment,st.track??'',st.ad??'',st.nextTrack??''].join(':'):'none';
T.setAudio=async(src,offset=0)=>{const abs=new URL(src,location.href).href;if(e.music.src!==abs)e.music.src=src;if(!e.music.duration||!Number.isFinite(e.music.duration))await new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;res()};e.music.addEventListener('loadedmetadata',f,{once:true});setTimeout(f,3000)});if(Number.isFinite(offset)&&offset>=0&&e.music.duration)try{e.music.currentTime=Math.min(offset,Math.max(0,e.music.duration-.08))}catch(_){}try{await e.music.play();return true}catch(_){return false}};
T.stopProgram=()=>{T.playEpoch++;try{e.music.onended=null;e.music.pause()}catch(_){}T.localKey=''};
T.nextStateAfter=st=>{if(st.segment==='track'){const next=(st.track+1)%T.TRACKS.length;if(T.adAfter(st.track)){const a=T.adIndexAfter(st.track);return{segment:'adJingle',ad:a,nextTrack:next,offset:0,dur:T.AD_JINGLE_DUR}}return{segment:'radioJingle',nextTrack:next,offset:0,dur:T.RADIO_JINGLE_DUR}}if(st.segment==='adJingle')return{segment:'ad',ad:st.ad,nextTrack:st.nextTrack,offset:0,dur:T.AD_DURS[st.ad]};if(st.segment==='ad')return{segment:'radioJingle',nextTrack:st.nextTrack,offset:0,dur:T.RADIO_JINGLE_DUR};if(st.segment==='radioJingle')return{segment:'track',track:st.nextTrack??0,offset:0,dur:T.TRACK_DURS[st.nextTrack??0]};return{segment:'track',track:0,offset:0,dur:T.TRACK_DURS[0]}};
T.playState=async(st,opt={})=>{if(!st)return false;const key=T.stateKey(st),src=T.srcFor(st),abs=new URL(src,location.href).href,same=key===T.localKey&&e.music.src===abs&&!e.music.paused;T.ui('music',st,true);if(same&&!opt.force){if(Number.isFinite(st.offset)&&Math.abs((e.music.currentTime||0)-st.offset)>2.5)try{e.music.currentTime=st.offset}catch(_){}return true}T.stopProgram();const epoch=T.playEpoch;T.localKey=key;const ok=await T.setAudio(src,st.offset||0);if(epoch!==T.playEpoch)return false;if(opt.autonext===false)e.music.onended=null;else e.music.onended=()=>{if(epoch!==T.playEpoch)return;T.playState(T.nextStateAfter(st),{force:true})};if(!ok)T.setStatus('warn','Нажми кнопку ещё раз, чтобы включить звук');else if(opt.status)T.setStatus('ok',opt.status);return ok};
T.playGlobalProgram=()=>T.playState(T.timelineState(),{force:true});
T.playOneShot=async(st)=>{T.stopProgram();const epoch=T.playEpoch;const ok=await T.setAudio(T.srcFor(st),st.offset||0);if(!ok)return false;await new Promise(res=>{let done=false;const finish=()=>{if(done)return;done=true;if(epoch===T.playEpoch){try{e.music.onended=null;e.music.pause()}catch(_){}}res()};e.music.onended=finish;setTimeout(finish,((st.dur||5)+1.5)*1000)});return true};
})();
(()=>{
'use strict';
const T=window.TM,e=T.el;
T.bootListener=async servers=>{let peer,control,call,wanted=false,mode='music',rt,lastRevision=0,applyToken=0;
 const closeLive=()=>{if(call){try{call.close()}catch(_){}call=null}try{e.live.pause()}catch(_){}e.live.srcObject=null};
 const specialState=d=>{const elapsed=Math.max(0,(Date.now()-(d.startedAt||Date.now()))/1000),dur=Number(d.dur)||5;return{segment:d.segment||'radioJingle',track:d.track,ad:d.ad,nextTrack:d.nextTrack,offset:Math.min(elapsed,Math.max(0,dur-.08)),dur}};
 const apply=async d=>{if(!d||d.type!=='state')return;const rev=Number(d.revision)||0;if(rev&&rev<lastRevision)return;const isNew=rev>lastRevision;if(rev)lastRevision=rev;const token=++applyToken;mode=d.mode||'music';if(!wanted)return;
  if(mode==='live'){closeLive();T.stopProgram();T.ui('live');T.setStatus('live','Подключаю микрофон ведущего…');return}
  if(mode!=='music'&&d.segment){closeLive();const st=specialState(d);T.ui(mode,st,true);const elapsed=Math.max(0,(Date.now()-(d.startedAt||Date.now()))/1000);if(elapsed>=st.dur-.05){T.stopProgram();T.setStatus('warn','Синхронизирую радио…');return}await T.playState(st,{force:true,autonext:false});if(token!==applyToken)return;const msg=st.segment==='adJingle'?'Рекламный джингл…':st.segment==='ad'?'Реклама…':mode==='intro'?'Джингл перед прямым эфиром…':mode==='outro'?'Джингл после эфира…':'Джингл • следующий трек…';T.setStatus('live',msg);return}
  if(mode==='music'){closeLive();const st={segment:d.segment||'track',track:d.track,ad:d.ad,nextTrack:d.nextTrack,offset:Number(d.offset)||0,dur:d.dur};await T.playState(st,{force:isNew||!!d.force,status:control?.open?'TomMart играет • студия на связи':'TomMart играет'});}
 };
 const reconnect=()=>{if(!wanted)return;clearTimeout(rt);rt=setTimeout(connect,T.CFG.reconnect)};
 const connect=()=>{if(!wanted||!peer?.open||control?.open)return;e.right.textContent='СВЯЗЬ…';control=peer.connect(T.CFG.host,{reliable:true,serialization:'json'});control.on('open',()=>{e.right.textContent='ONLINE';T.setStatus('ok','Студия на связи');control.send({type:'ready',at:Date.now()})});control.on('data',d=>apply(d));control.on('close',()=>{control=null;e.right.textContent='OFFLINE';reconnect()});control.on('error',()=>{control=null;reconnect()})};
 peer=new Peer(undefined,T.peerOpts(servers));peer.on('open',connect);peer.on('call',c=>{if(!wanted)return c.close();closeLive();call=c;T.stopProgram();T.ui('live');c.answer();c.on('stream',async s=>{e.live.srcObject=s;try{await e.live.play();T.setStatus('live','Ты слушаешь прямой эфир TomMart')}catch(_){e.btnText.textContent='ВКЛЮЧИТЬ ЗВУК LIVE';T.setStatus('warn','Эфир подключён — нажми кнопку')}});c.on('close',()=>{if(call===c)call=null});c.on('error',()=>T.setStatus('warn','Микрофон потерял связь'))});
 peer.on('error',x=>{if(x?.type==='peer-unavailable'){e.right.textContent='OFFLINE';reconnect()}else T.setStatus('warn','Связь: '+(x?.type||'ошибка'))});
 e.btn.disabled=false;e.btnText.textContent='СЛУШАТЬ TOMMART';e.right.textContent='ГОТОВО';T.setStatus('ok','Радио готово • нажми слушать');e.btn.onclick=async()=>{wanted=true;e.btn.disabled=true;await T.unlock();if(e.live.srcObject&&e.live.paused){try{await e.live.play()}catch(_){}e.btn.disabled=false;return}if(control?.open)control.send({type:'ready',at:Date.now()});else{await T.playGlobalProgram();connect()}setTimeout(()=>e.btn.disabled=false,450)};
};
})();
(()=>{
'use strict';
const T=window.TM,e=T.el;
T.bootAdmin=async servers=>{
 T.$('pillText').textContent='STUDIO';T.$('kicker').textContent='MOBILE BROADCAST STUDIO';T.$('title').innerHTML='ТВОЙ<br><span>ЭФИР.</span>';T.$('lead').textContent='Музыка идёт автоматически. Переключай следующий трек, запускай рекламу или выходи в прямой эфир — у всех слушателей синхронно.';T.$('disc').classList.add('hidden');T.$('micPanel').classList.remove('hidden');T.$('studioCard').classList.remove('hidden');T.$('playlistCard').classList.remove('hidden');T.$('note').classList.remove('hidden');T.$('leftLabel').textContent='СЛУШАТЕЛЕЙ';T.$('rightLabel').textContent='ЭФИР';e.left.textContent='0';e.right.textContent='OFF';
 const ps=T.$('peerState'),ms=T.$('micState'),mm=T.$('micMeter'),copy=T.$('copyBtn'),rows=T.$('playlistRows'),state=T.$('playlistState'),head=T.$('playlistCard').querySelector('.playlist-title span');if(head)head.textContent='УПРАВЛЕНИЕ РАДИО';
 let peer,mic,stopMeter,mode='music',busy=false,wake,anchorTrack=0,anchorAt=T.GLOBAL_ANCHOR,modeStartedAt=0,special=null,revision=Date.now(),manualAd=0,afterLiveTrack=0;const conns=new Map(),calls=new Map();
 const bump=()=>++revision;const current=()=>T.timelineState(anchorTrack,anchorAt);const count=()=>{let n=0;conns.forEach(c=>{if(c.open)n++});e.left.textContent=n;return n};
 const payload=()=>{if(mode==='live')return{type:'state',mode:'live',revision,startedAt:modeStartedAt,at:Date.now()};if(mode!=='music'&&special)return{type:'state',mode,revision,startedAt:modeStartedAt,...special,at:Date.now()};const s=current();return{type:'state',mode:'music',revision,segment:s.segment,track:s.track,ad:s.ad,nextTrack:s.nextTrack,offset:s.offset,dur:s.dur,at:Date.now()}};
 const send=c=>{if(c?.open)try{c.send(payload())}catch(_){}};const broadcast=()=>conns.forEach(send);
 const closeCall=id=>{const c=calls.get(id);if(c){try{c.close()}catch(_){}calls.delete(id)}};const callOne=id=>{if(mode!=='live'||!mic||!peer?.open)return;closeCall(id);try{const c=peer.call(id,mic,{metadata:{source:'tommart-live'}});if(c){calls.set(id,c);c.on('close',()=>calls.delete(id));c.on('error',()=>calls.delete(id))}}catch(_){}};
 const setSpecial=(newMode,st)=>{mode=newMode;modeStartedAt=Date.now();special={segment:st.segment,track:st.track,ad:st.ad,nextTrack:st.nextTrack,dur:st.dur};bump();draw();broadcast()};
 const setMusic=(track)=>{anchorTrack=track;anchorAt=Date.now();mode='music';modeStartedAt=0;special=null;bump();draw();broadcast()};
 const render=()=>{const cp=current(),info=T.titleFor(cp),next=T.nextTrackFrom(cp,anchorTrack),n=T.TRACKS[next];rows.innerHTML='';
  const r1=document.createElement('div');r1.className='track-row';r1.innerHTML='<div class="track-num">›</div><div class="track-info"><strong></strong><small></small></div><button class="track-play">СЛЕДУЮЩИЙ ТРЕК</button>';r1.querySelector('strong').textContent=info.title;r1.querySelector('small').textContent='ДАЛЬШЕ: '+n.title;const nextBtn=r1.querySelector('button');nextBtn.disabled=busy||mode!=='music';nextBtn.onclick=skipNext;rows.appendChild(r1);
  const r2=document.createElement('div');r2.className='track-row';r2.innerHTML='<div class="track-num">AD</div><div class="track-info"><strong>Рекламный блок</strong><small>ДЖИНГЛ → РЕКЛАМА → ДЖИНГЛ → МУЗЫКА</small></div><button class="track-play">ВКЛЮЧИТЬ РЕКЛАМУ</button>';const adBtn=r2.querySelector('button');adBtn.disabled=busy||mode!=='music';adBtn.onclick=playAdNow;rows.appendChild(r2);
 };
 function draw(){const cp=current();e.btn.disabled=!peer?.open||busy;e.btn.classList.toggle('on',mode==='live');e.btnText.textContent=mode==='live'?'ЗАВЕРШИТЬ ЭФИР':busy?'ПОДОЖДИ…':'ВЫЙТИ В ЭФИР';e.right.textContent=mode==='live'?'ON AIR':mode==='music'?'OFF':special?.segment==='ad'||special?.segment==='adJingle'?'AD':'JINGLE';ms.textContent=mic?'ACTIVE':'OFF';T.ui(mode==='music'?'music':mode,special||cp);render();state.textContent=busy?'ВЫПОЛНЯЮ':mode==='live'?'ЭФИР':'АВТО'}
 const runSegment=async st=>{T.ui('music',st,true);return T.playOneShot({...st,offset:0})};
 async function skipNext(){if(busy||mode!=='music')return;const target=T.nextTrackFrom(current(),anchorTrack);busy=true;setSpecial('switching',{segment:'radioJingle',nextTrack:target,dur:T.RADIO_JINGLE_DUR});T.setStatus('live','Радиоджингл • переключаю следующий трек…');await runSegment({segment:'radioJingle',nextTrack:target,dur:T.RADIO_JINGLE_DUR});setMusic(target);busy=false;draw();broadcast();T.setStatus('ok','Сейчас играет: '+T.TRACKS[target].title)}
 async function playAdNow(){if(busy||mode!=='music')return;busy=true;const target=T.nextTrackFrom(current(),anchorTrack),ad=manualAd++%T.ADS.length;
  setSpecial('manualAd',{segment:'adJingle',ad,nextTrack:target,dur:T.AD_JINGLE_DUR});T.setStatus('live','Рекламный джингл…');await runSegment({segment:'adJingle',ad,nextTrack:target,dur:T.AD_JINGLE_DUR});
  setSpecial('manualAd',{segment:'ad',ad,nextTrack:target,dur:T.AD_DURS[ad]});T.setStatus('live','Реклама '+(ad+1)+'…');await runSegment({segment:'ad',ad,nextTrack:target,dur:T.AD_DURS[ad]});
  setSpecial('manualAd',{segment:'radioJingle',nextTrack:target,dur:T.RADIO_JINGLE_DUR});T.setStatus('live','TomMart • возвращаемся к музыке…');await runSegment({segment:'radioJingle',nextTrack:target,dur:T.RADIO_JINGLE_DUR});
  setMusic(target);busy=false;draw();broadcast();T.setStatus('ok','Реклама закончилась • '+T.TRACKS[target].title)}
 async function startAir(){if(busy||mode==='live')return;busy=true;afterLiveTrack=T.nextTrackFrom(current(),anchorTrack);draw();T.setStatus('warn','Запрашиваю микрофон…');try{await T.unlock();mic=await navigator.mediaDevices.getUserMedia({video:false,audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});stopMeter=T.meter(mic,l=>mm.style.width=Math.max(3,Math.round(l*100))+'%');if('wakeLock'in navigator)try{wake=await navigator.wakeLock.request('screen')}catch(_){}setSpecial('intro',{segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});T.setStatus('live','Радиоджингл перед эфиром…');await runSegment({segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});mode='live';modeStartedAt=Date.now();special=null;bump();busy=false;draw();broadcast();conns.forEach((c,id)=>{if(c.open)callOne(id)});T.setStatus('live','ТЫ В ПРЯМОМ ЭФИРЕ')}catch(x){console.error(x);if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';busy=false;setMusic(afterLiveTrack);T.setStatus('bad',x?.name==='NotAllowedError'?'Нет доступа к микрофону':'Не удалось включить микрофон')}}
 async function stopAir(){if(busy||mode!=='live')return;busy=true;calls.forEach((_,id)=>closeCall(id));if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';setSpecial('outro',{segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});T.setStatus('live','Радиоджингл после эфира…');await runSegment({segment:'radioJingle',nextTrack:afterLiveTrack,dur:T.RADIO_JINGLE_DUR});setMusic(afterLiveTrack);busy=false;draw();broadcast();T.setStatus('ok','Музыка снова играет • студия готова');if(wake)try{await wake.release()}catch(_){}}
 e.btn.onclick=()=>mode==='live'?stopAir():startAir();copy.onclick=async()=>{let k='';try{k=localStorage.getItem('tommart_turn_key')||''}catch(_){}const u=new URL(location.origin+location.pathname);if(k)u.searchParams.set('turn',k);try{await navigator.clipboard.writeText(u.toString());copy.textContent='СКОПИРОВАНО';setTimeout(()=>copy.textContent='КОПИРОВАТЬ',1500)}catch(_){}};
 peer=new Peer(T.CFG.host,T.peerOpts(servers));peer.on('open',()=>{ps.textContent='ONLINE';draw();T.setStatus('ok','Студия онлайн • управление синхронизировано')});peer.on('connection',c=>{conns.set(c.peer,c);c.on('open',()=>{count();send(c);if(mode==='live'&&mic)setTimeout(()=>callOne(c.peer),150)});c.on('data',d=>{if(d?.type==='ready'){send(c);if(mode==='live'&&mic)setTimeout(()=>callOne(c.peer),150)}});c.on('close',()=>{conns.delete(c.peer);closeCall(c.peer);count()});c.on('error',()=>{conns.delete(c.peer);closeCall(c.peer);count()})});peer.on('error',x=>{ps.textContent=x?.type==='unavailable-id'?'BUSY':'ERROR';T.setStatus('bad',x?.type==='unavailable-id'?'Студия уже открыта на другом устройстве':'Ошибка PeerJS: '+(x?.type||'unknown'));draw()});setInterval(()=>{if(peer?.open){draw();broadcast()}},1800);draw();
};
})();
(async()=>{const T=window.TM;try{await T.loadDurations();const s=await T.getIce();if(T.IS_ADMIN){document.title='TomMart — Студия';await T.bootAdmin(s)}else await T.bootListener(s)}catch(e){console.error(e);T.el.btn.disabled=true;T.el.btnText.textContent=e.message==='TURN_KEY_MISSING'?'НУЖНА НАСТРОЙКА TURN':'ОШИБКА СВЯЗИ';T.setStatus('bad',e.message==='TURN_KEY_MISSING'?'Открой специальную ссылку TomMart для первого запуска':'Не удалось подключить TURN');T.el.right.textContent='ERROR'}})();
