(()=>{
'use strict';const T=window.TM,e=T.el;
T.bootAdmin=async servers=>{T.$('pillText').textContent='STUDIO';T.$('kicker').textContent='MOBILE BROADCAST STUDIO';T.$('title').innerHTML='ТВОЙ<br><span>ЭФИР.</span>';T.$('lead').textContent='Музыка идёт автоматически. «Следующий трек» включает радиоджингл и переключает песню. Перед рекламой звучит отдельный рекламный джингл.';T.$('disc').classList.add('hidden');T.$('micPanel').classList.remove('hidden');T.$('studioCard').classList.remove('hidden');T.$('playlistCard').classList.remove('hidden');T.$('note').classList.remove('hidden');T.$('leftLabel').textContent='СЛУШАТЕЛЕЙ';T.$('rightLabel').textContent='ЭФИР';e.left.textContent='0';e.right.textContent='OFF';
 const ps=T.$('peerState'),ms=T.$('micState'),mm=T.$('micMeter'),copy=T.$('copyBtn'),rows=T.$('playlistRows'),state=T.$('playlistState'),head=T.$('playlistCard').querySelector('.playlist-title span');if(head)head.textContent='УПРАВЛЕНИЕ МУЗЫКОЙ';let peer,mic,stopMeter,mode='music',busy=false,wake,anchorTrack=0,anchorAt=T.GLOBAL_ANCHOR,modeStartedAt=0;const conns=new Map(),calls=new Map();
 const current=()=>T.timelineState(anchorTrack,anchorAt);const count=()=>{let n=0;conns.forEach(c=>{if(c.open)n++});e.left.textContent=n;return n};
 const payload=()=>{if(mode!=='music')return{type:'state',mode,startedAt:modeStartedAt,nextTrack:T.nextTrackFrom(current(),anchorTrack),at:Date.now()};const s=current();return{type:'state',mode:'music',segment:s.segment,track:s.track,ad:s.ad,nextTrack:s.nextTrack,offset:s.offset,dur:s.dur,at:Date.now()}};
 const send=c=>{if(c?.open)try{c.send(payload())}catch(_){}};const broadcast=()=>conns.forEach(send);const closeCall=id=>{const c=calls.get(id);if(c){try{c.close()}catch(_){}calls.delete(id)}};const callOne=id=>{if(mode!=='live'||!mic||!peer?.open)return;closeCall(id);try{const c=peer.call(id,mic,{metadata:{source:'tommart-live'}});if(c){calls.set(id,c);c.on('close',()=>calls.delete(id));c.on('error',()=>calls.delete(id))}}catch(_){}};
 const render=()=>{const cp=current(),info=T.titleFor(cp),next=T.nextTrackFrom(cp,anchorTrack),n=T.TRACKS[next];rows.innerHTML='';const r=document.createElement('div');r.className='track-row';r.innerHTML='<div class="track-num">›</div><div class="track-info"><strong></strong><small></small></div><button class="track-play">СЛЕДУЮЩИЙ ТРЕК</button>';r.querySelector('strong').textContent=info.title;r.querySelector('small').textContent='ДАЛЬШЕ: '+n.title;const b=r.querySelector('button');b.disabled=busy||mode!=='music';b.onclick=skipNext;rows.appendChild(r)};
 const draw=()=>{const cp=current();e.btn.disabled=!peer?.open||busy;e.btn.classList.toggle('on',mode==='live');e.btnText.textContent=mode==='live'?'ЗАВЕРШИТЬ ЭФИР':busy?'ПОДОЖДИ…':'ВЫЙТИ В ЭФИР';e.right.textContent=mode==='live'?'ON AIR':mode==='music'?'OFF':'JINGLE';ms.textContent=mic?'ACTIVE':'OFF';T.ui(mode==='music'?'music':mode,cp);render();state.textContent=busy?'ПЕРЕКЛЮЧЕНИЕ':mode==='live'?'ЭФИР':'АВТО'};
 const radioJingle=async()=>{T.stopProgram();T.localKey='';const ok=await T.setAudio(T.pathFor(T.RADIO_JINGLE.file),0);if(!ok){T.setStatus('warn','iPhone не разрешил звук джингла — нажми ещё раз');return false}await new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;e.music.pause();e.music.onended=null;res()};e.music.onended=f;setTimeout(f,(T.RADIO_JINGLE_DUR+1.2)*1000)});return true};
 async function skipNext(){if(busy||mode!=='music')return;const target=T.nextTrackFrom(current(),anchorTrack);busy=true;mode='switching';modeStartedAt=Date.now();draw();broadcast();T.setStatus('live','Радиоджингл • переключаю следующий трек…');await radioJingle();anchorTrack=target;anchorAt=Date.now();mode='music';modeStartedAt=0;busy=false;draw();broadcast();T.setStatus('ok','Следующий трек: '+T.TRACKS[target].title)}
 async function startAir(){if(busy||mode==='live')return;busy=true;draw();T.setStatus('warn','Запрашиваю микрофон…');try{await T.unlock();mic=await navigator.mediaDevices.getUserMedia({video:false,audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});stopMeter=T.meter(mic,l=>mm.style.width=Math.max(3,Math.round(l*100))+'%');if('wakeLock'in navigator)try{wake=await navigator.wakeLock.request('screen')}catch(_){}mode='intro';modeStartedAt=Date.now();draw();broadcast();T.setStatus('live','Радиоджингл перед эфиром…');await radioJingle();mode='live';modeStartedAt=Date.now();busy=false;draw();broadcast();conns.forEach((c,id)=>{if(c.open)callOne(id)});T.setStatus('live','ТЫ В ПРЯМОМ ЭФИРЕ')}catch(x){console.error(x);if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';busy=false;mode='music';modeStartedAt=0;broadcast();draw();T.setStatus('bad',x?.name==='NotAllowedError'?'Нет доступа к микрофону':'Не удалось включить микрофон')}}
 async function stopAir(){if(busy||mode!=='live')return;busy=true;mode='outro';modeStartedAt=Date.now();draw();broadcast();calls.forEach((_,id)=>closeCall(id));if(mic)mic.getTracks().forEach(t=>t.stop());mic=null;if(stopMeter)stopMeter();stopMeter=null;mm.style.width='3%';T.setStatus('live','Радиоджингл после эфира…');await radioJingle();anchorAt=Date.now();mode='music';modeStartedAt=0;busy=false;draw();broadcast();T.setStatus('ok','Музыка снова играет • студия готова');if(wake)try{await wake.release()}catch(_){}}
 e.btn.onclick=()=>mode==='live'?stopAir():startAir();copy.onclick=async()=>{let k='';try{k=localStorage.getItem('tommart_turn_key')||''}catch(_){}const u=new URL(location.origin+location.pathname);if(k)u.searchParams.set('turn',k);try{await navigator.clipboard.writeText(u.toString());copy.textContent='СКОПИРОВАНО';setTimeout(()=>copy.textContent='КОПИРОВАТЬ',1500)}catch(_){}};
 peer=new Peer(T.CFG.host,T.peerOpts(servers));peer.on('open',()=>{ps.textContent='ONLINE';draw();T.setStatus('ok','Студия онлайн • музыка работает автоматически')});peer.on('connection',c=>{conns.set(c.peer,c);c.on('open',()=>{count();send(c);if(mode==='live'&&mic)setTimeout(()=>callOne(c.peer),150)});c.on('data',d=>{if(d?.type==='ready'){send(c);if(mode==='live'&&mic)setTimeout(()=>callOne(c.peer),150)}});c.on('close',()=>{conns.delete(c.peer);closeCall(c.peer);count()});c.on('error',()=>{conns.delete(c.peer);closeCall(c.peer);count()})});peer.on('error',x=>{ps.textContent=x?.type==='unavailable-id'?'BUSY':'ERROR';T.setStatus('bad',x?.type==='unavailable-id'?'Студия уже открыта на другом устройстве':'Ошибка PeerJS: '+(x?.type||'unknown'));draw()});setInterval(()=>{if(mode==='music'&&!busy){draw();broadcast()}},2500);draw();
};
})();
